dataset:
  _target_: opr.datasets.mipt_campus.MIPTCampusDataset

  # dataset_root: /home/docker_opr/Datasets/MIPT_Campus_preprocessed/splitted/train
  dataset_root: ./dataset/public
  modalities: [image, cloud, mask, text]
  cam_types: ['front', 'back']
  mink_quantization_size: 0.01

sampler:
  _target_: opr.datasets.samplers.batch_sampler.BatchSampler

  batch_size: 8
  batch_size_limit: 32
  batch_expansion_rate: 1.4
  positives_per_group: 2
  seed: 3121999

num_workers: 4
